import { WORKDAY_START, WORKDAY_END } from '@household/shared/constants';

type CalendarDayLimitTestCase = {
  earliestStart: number;
  latestEnd: number;
  plannedStart: number;
  plannedEnd: number;
  calculatedStart: number;
  calculatedEnd: number;
};

export const defaultDayLimitTestCases: CalendarDayLimitTestCase[] = [
  {
    earliestStart: 52,
    latestEnd: 60,
    plannedStart: WORKDAY_START,
    plannedEnd: WORKDAY_END,
    calculatedStart: 32,
    calculatedEnd: 80,
  },
  {
    earliestStart: 32,
    latestEnd: 52,
    plannedStart: WORKDAY_START,
    plannedEnd: WORKDAY_END,
    calculatedStart: 28,
    calculatedEnd: 60,
  },
  {
    earliestStart: 60,
    latestEnd: 80,
    plannedStart: WORKDAY_START,
    plannedEnd: WORKDAY_END,
    calculatedStart: 52,
    calculatedEnd: 84,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: WORKDAY_START,
    plannedEnd: WORKDAY_END,
    calculatedStart: 44,
    calculatedEnd: 68,
  },
];

export const dayLimitTestCases: CalendarDayLimitTestCase[] = [
  ...defaultDayLimitTestCases,
  {
    earliestStart: 40,
    latestEnd: 50,
    plannedStart: 32,
    plannedEnd: 48,
    calculatedStart: 32,
    calculatedEnd: 48,
  },
  {
    earliestStart: 28,
    latestEnd: 48,
    plannedStart: 32,
    plannedEnd: 64,
    calculatedStart: 32,
    calculatedEnd: 56,
  },
  {
    earliestStart: 48,
    latestEnd: 68,
    plannedStart: 32,
    plannedEnd: 64,
    calculatedStart: 40,
    calculatedEnd: 64,
  },
  {
    earliestStart: 56,
    latestEnd: 64,
    plannedStart: 32,
    plannedEnd: 48,
    calculatedStart: 36,
    calculatedEnd: 48,
  },
  {
    earliestStart: 48,
    latestEnd: 56,
    plannedStart: 64,
    plannedEnd: 80,
    calculatedStart: 64,
    calculatedEnd: 76,
  },
  {
    earliestStart: 68,
    latestEnd: 72,
    plannedStart: 32,
    plannedEnd: 40,
    calculatedStart: undefined,
    calculatedEnd: undefined,
  },
  {
    earliestStart: 24,
    latestEnd: 28,
    plannedStart: 56,
    plannedEnd: 64,
    calculatedStart: undefined,
    calculatedEnd: undefined,
  },
  {
    earliestStart: 68,
    latestEnd: 72,
    plannedStart: 48,
    plannedEnd: 60,
    calculatedStart: 48,
    calculatedEnd: 60,
  },
  {
    earliestStart: 24,
    latestEnd: 28,
    plannedStart: 36,
    plannedEnd: 48,
    calculatedStart: 36,
    calculatedEnd: 48,
  },
  {
    earliestStart: 40,
    latestEnd: 60,
    plannedStart: 44,
    plannedEnd: 56,
    calculatedStart: 44,
    calculatedEnd: 56,
  },
  {
    earliestStart: 44,
    latestEnd: 56,
    plannedStart: 40,
    plannedEnd: 64,
    calculatedStart: 40,
    calculatedEnd: 64,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: 42,
    plannedEnd: 70,
    calculatedStart: 44,
    calculatedEnd: 68,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: 48,
    plannedEnd: 64,
    calculatedStart: 48,
    calculatedEnd: 64,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: WORKDAY_START,
    plannedEnd: 70,
    calculatedStart: 44,
    calculatedEnd: 68,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: WORKDAY_START,
    plannedEnd: 56,
    calculatedStart: 44,
    calculatedEnd: 56,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: WORKDAY_START,
    plannedEnd: 42,
    calculatedStart: undefined,
    calculatedEnd: undefined,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: WORKDAY_START,
    plannedEnd: 36,
    calculatedStart: undefined,
    calculatedEnd: undefined,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: 42,
    plannedEnd: WORKDAY_END,
    calculatedStart: 44,
    calculatedEnd: 68,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: 48,
    plannedEnd: WORKDAY_END,
    calculatedStart: 48,
    calculatedEnd: 68,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: 70,
    plannedEnd: WORKDAY_END,
    calculatedStart: undefined,
    calculatedEnd: undefined,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: 76,
    plannedEnd: WORKDAY_END,
    calculatedStart: undefined,
    calculatedEnd: undefined,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: 42,
    plannedEnd: 64,
    calculatedStart: 44,
    calculatedEnd: 64,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: 48,
    plannedEnd: 70,
    calculatedStart: 48,
    calculatedEnd: 68,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: 41,
    plannedEnd: 42,
    calculatedStart: undefined,
    calculatedEnd: undefined,
  },
  {
    earliestStart: 40,
    latestEnd: 72,
    plannedStart: 70,
    plannedEnd: 71,
    calculatedStart: undefined,
    calculatedEnd: undefined,
  },
];
