import { Account, Calendar, Category, Customer, File, Price, Product, Project, Recipient, Transaction, User } from '@household/shared/types/types';
import { CustomerJob } from '@household/web/types/common';
import { Action, createActionGroup, emptyProps, props } from '@ngrx/store';

export const dialogActions = createActionGroup({
  source: 'Dialog',
  events: {
    'Create project': emptyProps(),
    'Update project': props<Project.Response>(),
    'Delete project': props<Project.Response>(),
    'Merge projects': props<Project.Response>(),
    'Create recipient': emptyProps(),
    'Update recipient': props<Recipient.Response>(),
    'Delete recipient': props<Recipient.Response>(),
    'Merge recipients': props<Recipient.Response>(),
    'Create category': emptyProps(),
    'Update category': props<Category.Response>(),
    'Delete category': props<Category.Response>(),
    'Merge categories': props<Category.Response>(),
    'Create product': props<Category.CategoryId>(),
    'Update product': props<{product: Product.Response} & Category.CategoryId>(),
    'Delete product': props<{product: Product.Response} & Category.CategoryId>(),
    'Merge products': props<{product: Product.Response} & Category.CategoryId>(),
    'Create account': emptyProps(),
    'Update account': props<Account.Response>(),
    'Delete account': props<Account.Response>(),
    'Create customer': emptyProps(),
    'Update customer': props<Customer.CustomerId>(),
    'Create customer job': props<Customer.CustomerId>(),
    'Update customer job': props<Customer.CustomerId & Customer.Job.Response>(),
    'Delete customer job': props<Customer.CustomerId & Customer.Job.Name>(),
    'Add customer to blacklist': props<Customer.CustomerId>(),
    'Delete customer from blacklist': props<Customer.CustomerId & {selectedCustomer: Customer.Response}>(),
    'Create price': emptyProps(),
    'Update price': props<Price.PriceId & Price.Response>(),
    'Delete price': props<Price.Response>(),
    'Import file': emptyProps(),
    'Delete file': props<File.Response>(),
    'Delete user': props<User.Email>(),
    'Delete draft transactions': props<{transactionIds: Transaction.Id[]}>(),
    'Delete transaction': props<Transaction.TransactionId & {navigationAction?: Action;}>(),
    'Create calendar entry': props<Calendar.Entry.EntryType>(),
    'Update calendar entry': props<Calendar.Entry.Response>(),
    'Delete calendar entry': props<Pick<Calendar.Entry.Response, 'calendarEntryId' | 'title'>>(),
    'Confirm calendar entry proposal': props<Calendar.DayProp & {customerJob: CustomerJob; timeInterval: Calendar.TimeInterval}>(),
    'Create calendar entry with proposal': props<Calendar.DayProp & {customerJob: CustomerJob; timeInterval: Calendar.TimeInterval}>(),
    'Open calendar entry': props<Calendar.Entry.Response>(),
    'Open cash payment': props<Calendar.Entry.CalendarEntryId>(),
    'Set work day': props<Exclude<Calendar.Day.Response, Calendar.Day.HolidayResponse>>(),
  },
});
