AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  Env:
    Type: String

Resources:
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/dependencies
      LayerName: !Sub Household-${Env}-DependenciesLayer
      RetentionPolicy: Delete
      CompatibleRuntimes:
        - nodejs20.x

  RumIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: true
      IdentityPoolName: !Sub Household-${Env}

  RumGuestRoleMapping:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref RumIdentityPool
      Roles:
        "unauthenticated": !GetAtt RumIdentityPoolRole.Arn

  RumIdentityPoolRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub Household-${Env}-RumIdentityPoolRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Action:
            - sts:AssumeRoleWithWebIdentity
          Principal:
            Federated:
              - cognito-identity.amazonaws.com
          Condition:
            StringEquals:
              cognito-identity.amazonaws.com:aud: !Ref RumIdentityPool
            ForAnyValue:StringLike:
              cognito-identity.amazonaws.com:amr: "unauthenticated"
      Policies:
        - PolicyName: RumPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - rum:PutRumEvents
                Resource: !Sub arn:aws:rum:${AWS::Region}:${AWS::AccountId}:appmonitor/Household-${Env}

  RumAppMonitor:
    Type: AWS::RUM::AppMonitor
    Properties:
      Domain: "*.losi999.hu"
      Name: !Sub Household-${Env}
      AppMonitorConfiguration:
        IdentityPoolId: !Ref RumIdentityPool
        SessionSampleRate: 1
        Telemetries:
          - errors
          - performance
          - http
        AllowCookies: true

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub Household-${Env}-LambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Action:
            - sts:AssumeRole
          Principal:
            Service:
              - lambda.amazonaws.com
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                  - sns:Publish
                  - xray:*
                  - cognito-idp:AdminCreateUser
                  - cognito-idp:AdminGetUser
                  - cognito-idp:AdminInitiateAuth
                  - cognito-idp:AdminAddUserToGroup
                  - cognito-idp:AdminSetUserPassword
                  - cloudformation:DescribeStacks
                  - lambda:InvokeFunction
                  - sqs:SendMessage
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource: "*"

  WebsiteBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  WebSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: HouseholdPolicy
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${WebsiteBucket.Arn}/*"
      Bucket: !Ref WebsiteBucket

Outputs:
  LambdaRoleArn:
    Value: !GetAtt LambdaRole.Arn
  WebsiteBucket:
    Value: !Ref WebsiteBucket
  DependenciesLayer:
    Value: !Ref DependenciesLayer
  RumAppMonitorId:
    Value: !GetAtt RumAppMonitor.Id
  RumIdentityPoolId:
    Value: !Ref RumIdentityPool
