AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Household Transaction Api"
Parameters:
  LambdaRoleArn:
    Type: String
  UserPoolArn:
    Type: String
  Env:
    Type: String
  MongodbConnectionString:
    Type: String
  DependenciesLayer:
    Type: String

Conditions:
  ShouldUseLayers: !Not [!Equals [!Ref DependenciesLayer, "DependenciesLayer"]]

Globals:
  Function:
    Handler: index.default
    Runtime: nodejs20.x
    Timeout: 60
    MemorySize: 512
    Tracing: Active
    Tags:
      Application: !Sub Household-${Env}
    Layers:
      - !If [ShouldUseLayers, !Ref DependenciesLayer, !Ref "AWS::NoValue"]
    Environment:
      Variables:
        MONGODB_CONNECTION_STRING: !Ref MongodbConnectionString

Resources:
  TransactionApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub Household-${Env}-Transaction
      StageName: transaction
      TracingEnabled: true
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref UserPoolArn
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'*'"
          ResponseTemplates:
            application/json: '{ "message": $context.error.messageString }'
        MISSING_AUTHENTICATION_TOKEN:
          StatusCode: 404
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'*'"
          ResponseTemplates:
            application/json: '{ "message": $context.error.messageString }'

  CreatePaymentTransaction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-CreatePaymentTransaction
      CodeUri: dist/api/create-payment-transaction
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref TransactionApi
            Path: /v1/transactions/payment
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  CreateSplitTransaction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-CreateSplitTransaction
      CodeUri: dist/api/create-split-transaction
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref TransactionApi
            Path: /v1/transactions/split
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  CreateTransferTransaction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-CreateTransferTransaction
      CodeUri: dist/api/create-transfer-transaction
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref TransactionApi
            Path: /v1/transactions/transfer
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  UpdateToPaymentTransaction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-UpdateToPaymentTransaction
      CodeUri: dist/api/update-to-payment-transaction
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref TransactionApi
            Path: /v1/transactions/{transactionId}/payment
            Method: PUT
            Auth:
              Authorizer: CognitoAuthorizer

  UpdateToSplitTransaction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-UpdateToSplitTransaction
      CodeUri: dist/api/update-to-split-transaction
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref TransactionApi
            Path: /v1/transactions/{transactionId}/split
            Method: PUT
            Auth:
              Authorizer: CognitoAuthorizer

  UpdateToTransferTransaction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-UpdateToTransferTransaction
      CodeUri: dist/api/update-to-transfer-transaction
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref TransactionApi
            Path: /v1/transactions/{transactionId}/transfer
            Method: PUT
            Auth:
              Authorizer: CognitoAuthorizer

  ListDeferredTransactions:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-ListDeferredTransactions
      CodeUri: dist/api/list-deferred-transactions
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref TransactionApi
            Path: /v1/transactions/deferred
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  GetTransaction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-GetTransaction
      CodeUri: dist/api/get-transaction
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref TransactionApi
            Path: /v1/accounts/{accountId}/transactions/{transactionId}
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  DeleteTransaction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-DeleteTransaction
      CodeUri: dist/api/delete-transaction
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref TransactionApi
            Path: /v1/transactions/{transactionId}
            Method: DELETE
            Auth:
              Authorizer: CognitoAuthorizer

  ListTransactionsByAccount:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-ListTransactionsByAccount
      CodeUri: dist/api/list-transactions-by-account
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref TransactionApi
            Path: /v1/accounts/{accountId}/transactions
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  ListTransactionsByFile:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-ListTransactionsByFile
      CodeUri: dist/api/list-transactions-by-file
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref TransactionApi
            Path: /v1/files/{fileId}/transactions
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  ReportTransactions:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-ReportTransactions
      CodeUri: dist/api/report-transactions
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref TransactionApi
            Path: /v1/transactionReports
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  TransactionApi:
    Description: "Household Transaction API"
    Value: !Sub "${TransactionApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}"
