AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Household Calendar Api"
Parameters:
  LambdaRoleArn:
    Type: String
  UserPoolArn:
    Type: String
  Env:
    Type: String
  MongodbConnectionString:
    Type: String
  DependenciesLayer:
    Type: String

Conditions:
  ShouldUseLayers: !Not [!Equals [!Ref DependenciesLayer, "DependenciesLayer"]]

Globals:
  Function:
    Handler: index.default
    Runtime: nodejs20.x
    Timeout: 60
    MemorySize: 512
    Tracing: Active
    Tags:
      Application: !Sub Household-${Env}
    Layers:
      - !If [ShouldUseLayers, !Ref DependenciesLayer, !Ref "AWS::NoValue"]
    Environment:
      Variables:
        MONGODB_CONNECTION_STRING: !Ref MongodbConnectionString

Resources:
  CalendarApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub Household-${Env}-Calendar
      StageName: calendar
      TracingEnabled: true
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref UserPoolArn
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'*'"
          ResponseTemplates:
            application/json: '{ "message": $context.error.messageString }'
        MISSING_AUTHENTICATION_TOKEN:
          StatusCode: 404
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'*'"
          ResponseTemplates:
            application/json: '{ "message": $context.error.messageString }'

  CreateCalendarEntry:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-CreateCalendarEntry
      CodeUri: dist/api/create-calendar-entry
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref CalendarApi
            Path: /v1/entries
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  GetCalendarEntry:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-GetCalendarEntry
      CodeUri: dist/api/get-calendar-entry
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref CalendarApi
            Path: /v1/entries/{calendarEntryId}
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  UpdateCalendarEntry:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-UpdateCalendarEntry
      CodeUri: dist/api/update-calendar-entry
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref CalendarApi
            Path: /v1/entries/{calendarEntryId}
            Method: PUT
            Auth:
              Authorizer: CognitoAuthorizer

  DeleteCalendarEntry:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-DeleteCalendarEntry
      CodeUri: dist/api/delete-calendar-entry
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref CalendarApi
            Path: /v1/entries/{calendarEntryId}
            Method: DELETE
            Auth:
              Authorizer: CognitoAuthorizer

  UpdateCalendarDay:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-UpdateCalendarDay
      CodeUri: dist/api/update-calendar-day
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref CalendarApi
            Path: /v1/days/{day}
            Method: PUT
            Auth:
              Authorizer: CognitoAuthorizer

  DeleteCalendarDay:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-DeleteCalendarDay
      CodeUri: dist/api/delete-calendar-day
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref CalendarApi
            Path: /v1/days/{day}
            Method: DELETE
            Auth:
              Authorizer: CognitoAuthorizer

  ListCalendarDays:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-ListCalendarDays
      CodeUri: dist/api/list-calendar-days
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref CalendarApi
            Path: /v1/days
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  ResolveCalendarWorkEntry:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Household-${Env}-ResolveCalendarWorkEntry
      CodeUri: dist/api/resolve-calendar-work-entry
      Role: !Ref LambdaRoleArn
      Events:
        API:
          Type: Api
          Properties:
            RestApiId: !Ref CalendarApi
            Path: /v1/entries/{calendarEntryId}/resolution
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  CalendarApi:
    Description: "Household Calendar API"
    Value: !Sub "${CalendarApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}"
