version: 2.1
parameters:
  deploy:
    type: boolean
    default: false
  skip_api_tests:
    type: boolean
    default: false
orbs:
  sam: circleci/aws-sam-serverless@6.0.3
jobs:
  setup:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Calculate config values
          command: |
            CYPRESS_PASSWORD="${CYPRESS_PASSWORD}"
            case "$CIRCLE_BRANCH" in
              master) ENV="PROD" 
              CYPRESS_PASSWORD="" ;;
              development) ENV="DEV" ;;
              *) ENV="LOCAL" ;;
            esac
            echo "ENV=$ENV" >> .config
            echo "CYPRESS_ENV=$ENV" >> .config
            echo "CYPRESS_PASSWORD=$CYPRESS_PASSWORD" >> .config
      - run: "cat .config"
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  install:
    docker:
      - image: cimg/node:22.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: cache-yarn-v1-{{checksum "yarn.lock"}}-{{checksum "web/yarn.lock"}}
      - run:
          name: Install API dependencies
          command: yarn
      - run:
          name: Install web dependencies
          command: yarn
          working_directory: web
      - run:
          name: Installing layer dependencies
          command: yarn install --modules-folder layers/dependencies/nodejs/node_modules --prod
      - save_cache:
          key: cache-yarn-v1-{{checksum "yarn.lock"}}-{{checksum "web/yarn.lock"}}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  unit_test:
    docker:
      - image: cimg/node:22.5
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Running API unit tests
          command: yarn test:api

      # - run:
      #     name: Running Web unit tests
      #     command: yarn test:web

      - store_artifacts:
          path: coverage
          destination: coverage
  lint:
    docker:
      - image: cimg/node:22.5
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Running linter
          command: yarn lint
  build:
    docker:
      - image: cimg/node:22.5
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: cat .config >> $BASH_ENV

      - run:
          name: Build API
          command: yarn build:api

      - run:
          name: Build Web
          command: yarn build:web -c $ENV

      - persist_to_workspace:
          root: ~/
          paths:
            - repo/dist
            - repo/layers
  api_deploy:
    executor: sam/default
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: cat .config >> $BASH_ENV
      - sam/install
      - deploy:
          name: SAM Deploy
          command: sam deploy --template-file cf.household.yaml --s3-bucket ${AWS_PACKAGES_S3} --stack-name Household-$ENV --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM --parameter-overrides Env=$ENV TestUserPassword=$CYPRESS_PASSWORD
      - run:
          name: Invoke Post deploy Lambda
          command: aws lambda invoke --function-name Household-$ENV-PostDeploy /dev/null
  web_deploy:
    docker:
      - image: cibuilds/aws:1.16.1
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: cat .config >> $BASH_ENV
      - run:
          name: Insert RUM App Monitor Id
          command: sed -i -e "s/RUM_APP_MONITOR_ID/$(aws cloudformation describe-stacks --stack-name Household-$ENV --query 'Stacks[0].Outputs[?OutputKey==`RumAppMonitorId`].OutputValue'  --output text)/g" ./dist/web/browser/index.html
      - run:
          name: Insert RUM Identity Pool Id
          command: sed -i -e "s/RUM_IDENTITY_POOL_ID/$(aws cloudformation describe-stacks --stack-name Household-$ENV --query 'Stacks[0].Outputs[?OutputKey==`RumIdentityPoolId`].OutputValue'  --output text)/g" ./dist/web/browser/index.html
      - deploy:
          name: Web deploy
          command: aws s3 sync dist/web/browser s3://$(aws cloudformation describe-stacks --stack-name Household-$ENV --query "Stacks[0].Outputs[?OutputKey=='WebsiteBucket'].OutputValue" --output text)
  api_test_setup:
    docker:
      - image: cibuilds/aws:1.16.1
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: cat .config >> $BASH_ENV
      - run:
          name: Getting MongoDB connection string
          command: echo "MONGODB_CONNECTION_STRING=\"mongodb+srv://$MONGODB_USERNAME:$MONGODB_PASSWORD@$MONGODB_CLUSTER_DOMAIN/household-$ENV?retryWrites=true&w=majority\"" >> .test_config
      - run:
          name: Getting Cognito user pool Id
          command: echo "USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name Household-$ENV --query 'Stacks[0].Outputs[?OutputKey==`CognitoUserPoolId`].OutputValue'  --output text) >> .test_config
      - run: "cat .test_config"
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  test:
    parameters:
      testCommand:
        type: string
    docker:
      - image: cypress/base:16.14.2
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: cat .config >> $BASH_ENV
      - run: cat .test_config >> $BASH_ENV
      - restore_cache:
          key: cache-cypress-v4-{{checksum "test/yarn.lock"}}
      - run:
          name: Install test dependencies
          command: yarn
          working_directory: test
      - save_cache:
          key: cache-cypress-v4-{{checksum "test/yarn.lock"}}
          paths:
            - /root/.cache/Cypress
      # - run:
      #     name: Setting MongoDB connection string
      #     command: echo "export MONGODB_CONNECTION_STRING=\"mongodb+srv://$MONGODB_USERNAME:$MONGODB_PASSWORD@$MONGODB_CLUSTER_DOMAIN/household-$ENV?retryWrites=true&w=majority\"" >> "$BASH_ENV"

      - run:
          name: Running tests
          working_directory: test
          command: yarn run test:<<parameters.testCommand>>

      - store_artifacts:
          path: test/cypress/screenshots
          destination: test/cypress/screenshots
workflows:
  local:
    jobs:
      - setup
      - install:
          requires:
            - setup
          # filters:
          #   branches:
          #     ignore:
          #       - development
          #       - master
      - unit_test:
          name: unit_test
          requires:
            - install
      - lint:
          name: lint
          requires:
            - install
      - build:
          name: build
          requires:
            - install
      - api_deploy:
          name: api_deploy
          filters: pipeline.git.branch == "master" or pipeline.git.branch == "development" or pipeline.parameters.deploy
          requires:
            - unit_test
            - lint
            - build
      - web_deploy:
          name: web_deploy
          requires:
            - api_deploy
      - api_test_setup:
          requires:
            - web_deploy
          filters: pipeline.parameters.skip_api_tests != true
      - test:
          name: test_account
          testCommand: "account"
          requires:
            - api_test_setup
      # - test:
      #     name: test_category
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "category"
      #     requires:
      #       - api_test_setup
      # - test:
      #     name: test_project
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "project"
      #     requires:
      #       - api_test_setup
      # - test:
      #     name: test_product
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "product"
      #     requires:
      #       - api_test_setup
      # - test:
      #     name: test_recipient
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "recipient"
      #     requires:
      #       - api_test_setup
      # - test:
      #     name: test_transaction_common
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "transaction-common"
      #     requires:
      #       - api_test_setup
      # - test:
      #     name: test_transaction_payment
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "transaction-payment"
      #     requires:
      #       - api_test_setup
      # - test:
      #     name: test_transaction_deferred
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "transaction-deferred"
      #     requires:
      #       - api_test_setup
      # - test:
      #     name: test_transaction_split
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "transaction-split"
      #     requires:
      #       - api_test_setup
      # - test:
      #     name: test_transaction_reimbursement
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "transaction-reimbursement"
      #     requires:
      #       - api_test_setup
      # - test:
      #     name: test_transaction_transfer
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "transaction-transfer"
      #     requires:
      #       - api_test_setup
      # - test:
      #     name: test_setting
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "setting"
      #     requires:
      #       - api_test_setup
      - test:
          name: test_user
          filters: pipeline.parameters.skip_api_tests != true
          testCommand: "user"
          requires:
            - api_test_setup
      # - test:
      #     name: test_file
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "file"
      #     requires:
      #       - api_test_setup
