version: 2.1
parameters:
  deploy_to_local:
    type: boolean
    default: false
  skip_api_tests:
    type: boolean
    default: false
orbs:
  sam: circleci/aws-sam-serverless@6.0.3
jobs:
  setup:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Calculate config values
          command: |
            case "$CIRCLE_BRANCH" in
              master) ENV="PROD" ;;
              development) ENV="DEV" ;;
              *) ENV="LOCAL" ;;
            esac
            echo "ENV=$ENV" > .env
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  testing:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: "pwd"
      - run: "ls -la"
      - run: "cat .env"
      - run:
          name: Load .env File
          command: |
            set -o allexport
            source .env
            set +o allexport
      - run:
          name: Print config values
          command: echo "$ENV"
  install:
    docker:
      - image: cimg/node:22.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: cache-yarn-v1-{{checksum "yarn.lock"}}-{{checksum "web/yarn.lock"}}
      - run:
          name: Install API dependencies
          command: yarn
      - run:
          name: Install web dependencies
          command: yarn
          working_directory: web
      - run:
          name: Installing layer dependencies
          command: yarn install --modules-folder layers/dependencies/nodejs/node_modules --prod
      - save_cache:
          key: cache-yarn-v1-{{checksum "yarn.lock"}}-{{checksum "web/yarn.lock"}}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  unit_test:
    docker:
      - image: cimg/node:22.5
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Running API unit tests
          command: yarn test:api

      # - run:
      #     name: Running Web unit tests
      #     command: yarn test:web

      - store_artifacts:
          path: coverage
          destination: coverage
  lint:
    docker:
      - image: cimg/node:22.5
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Running linter
          command: yarn lint
  build:
    parameters:
      env:
        type: string
    docker:
      - image: cimg/node:22.5
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Build API
          command: yarn build:api

      - run:
          name: Build Web
          command: yarn build:web -c <<parameters.env>>

      - persist_to_workspace:
          root: ~/
          paths:
            - repo/dist
            - repo/layers
  api_deploy:
    executor: sam/default
    parameters:
      env:
        type: string
      cypress_password:
        type: string
        default: ${CYPRESS_PASSWORD}
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - sam/install
      - deploy:
          name: SAM Deploy
          command: sam deploy --template-file cf.household.yaml --s3-bucket ${AWS_PACKAGES_S3} --stack-name Household-<<parameters.env>> --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM --parameter-overrides Env=<<parameters.env>> TestUserPassword=<<parameters.cypress_password>>
      - run:
          name: Invoke Post deploy Lambda
          command: aws lambda invoke --function-name Household-<<parameters.env>>-PostDeploy /dev/null
  web_deploy:
    parameters:
      env:
        type: string
    docker:
      - image: cibuilds/aws:1.16.1
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Insert RUM App Monitor Id
          command: sed -i -e "s/RUM_APP_MONITOR_ID/$(aws cloudformation describe-stacks --stack-name Household-<<parameters.env>> --query 'Stacks[0].Outputs[?OutputKey==`RumAppMonitorId`].OutputValue'  --output text)/g" ./dist/web/browser/index.html
      - run:
          name: Insert RUM Identity Pool Id
          command: sed -i -e "s/RUM_IDENTITY_POOL_ID/$(aws cloudformation describe-stacks --stack-name Household-<<parameters.env>> --query 'Stacks[0].Outputs[?OutputKey==`RumIdentityPoolId`].OutputValue'  --output text)/g" ./dist/web/browser/index.html
      - deploy:
          name: Web deploy
          command: aws s3 sync dist/web/browser s3://$(aws cloudformation describe-stacks --stack-name Household-<<parameters.env>> --query "Stacks[0].Outputs[?OutputKey=='WebsiteBucket'].OutputValue" --output text)
  test:
    parameters:
      env:
        type: string
      testCommand:
        type: string
    docker:
      - image: cypress/base:16.14.2
    environment:
      ENV: <<parameters.env>>
      CYPRESS_ENV: <<parameters.env>>
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: cache-cypress-v4-{{checksum "test/yarn.lock"}}
      - run:
          name: Install test dependencies
          command: yarn
          working_directory: test
      - save_cache:
          key: cache-cypress-v4-{{checksum "test/yarn.lock"}}
          paths:
            - /root/.cache/Cypress
      - run:
          name: Setting MongoDB connection string
          command: echo "export MONGODB_CONNECTION_STRING=\"mongodb+srv://$MONGODB_USERNAME:$MONGODB_PASSWORD@$MONGODB_CLUSTER_DOMAIN/household-<<parameters.env>>?retryWrites=true&w=majority\"" >> "$BASH_ENV"

      - when:
          condition:
            equal: ["LOCAL", <<parameters.env>>]
          steps:
            - run:
                name: Verify cypress
                working_directory: test
                command: yarn verify

      - when:
          condition:
            not:
              equal: ["LOCAL", <<parameters.env>>]
          steps:
            - run:
                name: Running tests
                working_directory: test
                command: yarn run test:<<parameters.testCommand>>

      - store_artifacts:
          path: test/cypress/screenshots
          destination: test/cypress/screenshots
workflows:
  setup:
    jobs:
      - setup
      - testing:
          requires:
            - setup
      # - install:
      #     name: install
      #     filters:
      #       branches:
      #         ignore:
      #           - development
      #           - master
      # - unit_test:
      #     name: unit_test
      #     requires:
      #       - install
      # - lint:
      #     name: lint
      #     requires:
      #       - install
      # - build:
      #     name: build
      #     env: "LOCAL"
      #     requires:
      #       - install
      # - test:
      #     name: test
      #     filters: pipeline.parameters.deploy_to_local != true
      #     env: "LOCAL"
      #     testCommand: ""
      #     requires:
      #       - install
      # - api_deploy:
      #     name: api_deploy
      #     env: "LOCAL"
      #     filters: pipeline.parameters.deploy_to_local
      #     requires:
      #       - unit_test
      #       - lint
      #       - build
      # - web_deploy:
      #     name: web_deploy
      #     env: "LOCAL"
      #     requires:
      #       - api_deploy
      # - test:
      #     name: test_account
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "account"
      #     requires:
      #       - web_deploy
      # - test:
      #     name: test_category
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "category"
      #     requires:
      #       - web_deploy
      # - test:
      #     name: test_project
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "project"
      #     requires:
      #       - web_deploy
      # - test:
      #     name: test_product
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "product"
      #     requires:
      #       - web_deploy
      # - test:
      #     name: test_recipient
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "recipient"
      #     requires:
      #       - web_deploy
      # - test:
      #     name: test_transaction_common
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "transaction-common"
      #     requires:
      #       - web_deploy
      # - test:
      #     name: test_transaction_payment
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "transaction-payment"
      #     requires:
      #       - web_deploy
      # - test:
      #     name: test_transaction_deferred
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "transaction-deferred"
      #     requires:
      #       - web_deploy
      # - test:
      #     name: test_transaction_split
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "transaction-split"
      #     requires:
      #       - web_deploy
      # - test:
      #     name: test_transaction_reimbursement
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "transaction-reimbursement"
      #     requires:
      #       - web_deploy
      # - test:
      #     name: test_transaction_transfer
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "transaction-transfer"
      #     requires:
      #       - web_deploy
      # - test:
      #     name: test_setting
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "setting"
      #     requires:
      #       - web_deploy
      # - test:
      #     name: test_user
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "user"
      #     requires:
      #       - web_deploy
      # - test:
      #     name: test_file
      #     filters: pipeline.parameters.skip_api_tests != true
      #     env: "LOCAL"
      #     testCommand: "file"
      #     requires:
      #       - web_deploy

  # dev:
  #   jobs:
  #     - install:
  #         name: install
  #         filters:
  #           branches:
  #             only:
  #               - development
  #     - unit_test:
  #         name: unit_test
  #         requires:
  #           - install
  #     - lint:
  #         name: lint
  #         requires:
  #           - install
  #     - build:
  #         name: build
  #         env: "DEV"
  #         requires:
  #           - install
  #     - api_deploy:
  #         name: api_deploy
  #         env: "DEV"
  #         requires:
  #           - unit_test
  #           - lint
  #           - build
  #     - web_deploy:
  #         name: web_deploy
  #         env: "DEV"
  #         requires:
  #           - api_deploy
  #     - test:
  #         name: test_account
  #         env: "DEV"
  #         testCommand: "account"
  #         requires:
  #           - web_deploy
  #     - test:
  #         name: test_category
  #         env: "DEV"
  #         testCommand: "category"
  #         requires:
  #           - web_deploy
  #     - test:
  #         name: test_project
  #         env: "DEV"
  #         testCommand: "project"
  #         requires:
  #           - web_deploy
  #     - test:
  #         name: test_product
  #         env: "DEV"
  #         testCommand: "product"
  #         requires:
  #           - web_deploy
  #     - test:
  #         name: test_recipient
  #         env: "DEV"
  #         testCommand: "recipient"
  #         requires:
  #           - web_deploy
  #     - test:
  #         name: test_transaction_common
  #         env: "DEV"
  #         testCommand: "transaction-common"
  #         requires:
  #           - web_deploy
  #     - test:
  #         name: test_transaction_payment
  #         env: "DEV"
  #         testCommand: "transaction-payment"
  #         requires:
  #           - web_deploy
  #     - test:
  #         name: test_transaction_deferred
  #         env: "DEV"
  #         testCommand: "transaction-deferred"
  #         requires:
  #           - web_deploy
  #     - test:
  #         name: test_transaction_split
  #         env: "DEV"
  #         testCommand: "transaction-split"
  #         requires:
  #           - web_deploy
  #     - test:
  #         name: test_transaction_reimbursement
  #         env: "DEV"
  #         testCommand: "transaction-reimbursement"
  #         requires:
  #           - web_deploy
  #     - test:
  #         name: test_transaction_transfer
  #         env: "DEV"
  #         testCommand: "transaction-transfer"
  #         requires:
  #           - web_deploy
  #     - test:
  #         name: test_setting
  #         env: "DEV"
  #         testCommand: "setting"
  #         requires:
  #           - web_deploy
  #     - test:
  #         name: test_user
  #         env: "DEV"
  #         testCommand: "user"
  #         requires:
  #           - web_deploy
  #     # - test:
  #     #     name: test_file
  #     #     env: "DEV"
  #     #     testCommand: "file"
  #     #     requires:
  #     #       - web_deploy

  # prod:
  #   jobs:
  #     - install:
  #         name: install
  #         filters:
  #           branches:
  #             only:
  #               - master
  #     - unit_test:
  #         name: unit_test
  #         requires:
  #           - install
  #     - lint:
  #         name: lint
  #         requires:
  #           - install
  #     - build:
  #         name: build
  #         env: "PROD"
  #         requires:
  #           - install
  #     - api_deploy:
  #         name: api_deploy
  #         env: "PROD"
  #         cypress_password: '"''''"'
  #         requires:
  #           - unit_test
  #           - lint
  #           - build
  #     - web_deploy:
  #         name: web_deploy
  #         env: "PROD"
  #         requires:
  #           - api_deploy
