version: 2.1
parameters:
  deploy:
    type: boolean
    default: false
  skip_api_tests:
    type: boolean
    default: false
commands:
  load-config:
    description: Load env config
    steps:
      - run:
          name: Load env config
          command: cat .config >> $BASH_ENV
orbs:
  sam: circleci/aws-sam-serverless@6.0.3
  browser-tools: circleci/browser-tools@2.3.2

jobs:
  install:
    docker:
      - image: cimg/node:24.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: cache-yarn-v1-{{checksum "yarn.lock"}}-{{checksum "web/yarn.lock"}}-{{checksum "web_legacy/yarn.lock"}}
      - run:
          name: Install API dependencies
          command: yarn
      - run:
          name: Install web dependencies
          command: yarn
          working_directory: web
      - run:
          name: Install web (Legacy) dependencies
          command: yarn
          working_directory: web_legacy
      - run:
          name: Install layer dependencies
          command: yarn install --modules-folder layers/dependencies/nodejs/node_modules --prod
      - save_cache:
          key: cache-yarn-v1-{{checksum "yarn.lock"}}-{{checksum "web/yarn.lock"}}-{{checksum "web_legacy/yarn.lock"}}
          paths:
            - ~/.cache/yarn
      - run:
          name: Calculate config values
          command: |
            case "$CIRCLE_BRANCH" in
              master) ENV="PROD" ;;
              development) ENV="DEV" ;;
              *) ENV="LOCAL" ;;
            esac
            echo "ENV=$ENV" >> .config
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  unit_test_api:
    docker:
      - image: cimg/node:24.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Running unit tests
          command: yarn test:api

      - store_artifacts:
          path: coverage
          destination: coverage
  unit_test_web_legacy:
    docker:
      - image: cimg/node:24.0-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - browser-tools/install_chrome

      - run:
          name: Running unit tests
          command: yarn test:web_legacy

      - store_artifacts:
          path: coverage
          destination: coverage

  unit_test_web_hairdressing:
    docker:
      - image: cimg/node:24.0-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - browser-tools/install_chrome

      - run:
          name: Running unit tests
          command: yarn test:hairdressing

      - store_artifacts:
          path: coverage
          destination: coverage

  unit_test_web_shared_ui:
    docker:
      - image: cimg/node:24.0-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - browser-tools/install_chrome

      - run:
          name: Running unit tests
          command: yarn test:shared-ui

      - store_artifacts:
          path: coverage
          destination: coverage          
  
  lint:
    docker:
      - image: cimg/node:24.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Running linter
          command: yarn lint
  build:
    docker:
      - image: cimg/node:24.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - load-config

      - run:
          name: Build API
          command: yarn build:api

      - run:
          name: Build Hairdressing Web
          command: yarn build:hairdressing

      - run:
          name: Build Web (Legacy)
          command: yarn build:web -c $ENV

      - persist_to_workspace:
          root: ~/
          paths:
            - repo/dist
            - repo/layers
  api_deploy:
    executor: sam/default
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - load-config
      - sam/install
      - deploy:
          name: SAM Deploy
          command: sam deploy --template-file cf.household.yaml --s3-bucket ${AWS_PACKAGES_S3} --stack-name Household-$ENV --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM --parameter-overrides Env=$ENV TestUserPassword=${PASSWORD}
      - run:
          name: Invoke Post deploy Lambda
          command: aws lambda invoke --function-name Household-$ENV-PostDeploy /dev/null

  web_hairdressing_deploy:
    executor: sam/default
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - load-config
      - sam/install
      - deploy:
          name: SAM Deploy
          command: sam deploy --template-file cf.hairdressing.yaml --s3-bucket ${AWS_PACKAGES_S3} --stack-name HairdressingWeb-$ENV --capabilities CAPABILITY_NAMED_IAM --parameter-overrides Env=$ENV --no-fail-on-empty-changeset
      - run:
          name: Insert RUM App Monitor Id
          command: sed -i -e "s/RUM_APP_MONITOR_ID/$(aws cloudformation describe-stacks --stack-name HairdressingWeb-$ENV --query 'Stacks[0].Outputs[?OutputKey==`RumAppMonitorId`].OutputValue' --output text)/g" ./dist/web_legacy/browser/index.html
      - run:
          name: Insert RUM Identity Pool Id
          command: sed -i -e "s/RUM_IDENTITY_POOL_ID/$(aws cloudformation describe-stacks --stack-name HairdressingWeb-$ENV --query 'Stacks[0].Outputs[?OutputKey==`RumIdentityPoolId`].OutputValue' --output text)/g" ./dist/web_legacy/browser/index.html
      - deploy:
          name: Web deploy
          command: aws s3 sync dist/hairdressing/browser s3://$(aws cloudformation describe-stacks --stack-name HairdressingWeb-$ENV --query "Stacks[0].Outputs[?OutputKey=='WebsiteBucket'].OutputValue" --output text)          
  web_legacy_deploy:
    docker:
      - image: cibuilds/aws:1.16.1
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - load-config
      - run:
          name: Insert RUM App Monitor Id
          command: sed -i -e "s/RUM_APP_MONITOR_ID/$(aws cloudformation describe-stacks --stack-name Household-$ENV --query 'Stacks[0].Outputs[?OutputKey==`RumAppMonitorId`].OutputValue' --output text)/g" ./dist/web_legacy/browser/index.html
      - run:
          name: Insert RUM Identity Pool Id
          command: sed -i -e "s/RUM_IDENTITY_POOL_ID/$(aws cloudformation describe-stacks --stack-name Household-$ENV --query 'Stacks[0].Outputs[?OutputKey==`RumIdentityPoolId`].OutputValue' --output text)/g" ./dist/web_legacy/browser/index.html
      - deploy:
          name: Web deploy
          command: aws s3 sync dist/web_legacy/browser s3://$(aws cloudformation describe-stacks --stack-name Household-$ENV --query "Stacks[0].Outputs[?OutputKey=='WebsiteBucket'].OutputValue" --output text)
  api_test_setup:
    docker:
      - image: cibuilds/aws:1.16.1
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - load-config
      - run: cat .config >> test/.env
      - run:
          name: Getting MongoDB connection string
          command: echo "MONGODB_CONNECTION_STRING=\"mongodb+srv://$MONGODB_USERNAME:$MONGODB_PASSWORD@$MONGODB_CLUSTER_DOMAIN/household-$ENV?retryWrites=true&w=majority&tls=true\"" >> test/.env
      - run:
          name: Getting Base URL
          command: echo "BASE_URL=\"$(aws cloudformation describe-stacks --stack-name Household-$ENV --query 'Stacks[0].Outputs[?OutputKey==`HouseholdApi`].OutputValue' --output text)\"" >> test/.env
      - run:
          name: Getting Cognito user pool Id
          command: echo "USER_POOL_ID=\"$(aws cloudformation describe-stacks --stack-name Household-$ENV --query 'Stacks[0].Outputs[?OutputKey==`CognitoUserPoolId`].OutputValue' --output text)\"" >> test/.env
      - run:
          name: Getting Import bucket name
          command: echo "IMPORT_BUCKET=\"$(aws cloudformation describe-stacks --stack-name Household-$ENV --query 'Stacks[0].Outputs[?OutputKey==`ImportBucket`].OutputValue' --output text)\"" >> test/.env
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  test:
    parameters:
      testCommand:
        type: string
    docker:
      - image: mcr.microsoft.com/playwright:v1.49.0-noble
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - load-config
      - restore_cache:
          key: cache-playwright-v1-{{checksum "test/yarn.lock"}}
      - run:
          name: Install test dependencies
          command: yarn
          working_directory: test
      - save_cache:
          key: cache-playwright-v1-{{checksum "test/yarn.lock"}}
          paths:
            - ~/.cache/yarn
      - run:
          name: Running tests
          working_directory: test
          command: export ENV=$ENV && yarn run test:<<parameters.testCommand>>
      - store_artifacts:
          path: test/playwright-report
          destination: test/playwright-report/<<parameters.testCommand>>
workflows:
  local:
    jobs:
      - install
      - unit_test_api:
          name: unit_test_api
          requires:
            - install
      - unit_test_web_legacy:
          name: unit_test_web_legacy
          requires:
            - install
      - unit_test_web_hairdressing:
          name: unit_test_web_hairdressing
          requires:
            - install
      - unit_test_web_shared_ui:
          name: unit_test_web_shared_ui
          requires:
            - install
      - lint:
          name: lint
          requires:
            - install
      - build:
          name: build
          requires:
            - install
      - api_deploy:
          name: api_deploy
          filters: pipeline.git.branch == "master" or pipeline.git.branch == "development" or pipeline.parameters.deploy
          requires:
            - unit_test_api
            # - unit_test_web_legacy
            # - unit_test_web_hairdressing
            # - unit_test_web_shared_ui
            - lint
            - build
      - web_hairdressing_deploy:
          name: web_hairdressing_deploy
          requires:
            - api_deploy
      - web_legacy_deploy:
          name: web_legacy_deploy
          requires:
            - api_deploy
      - api_test_setup:
          requires:
            - api_deploy
          filters: pipeline.git.branch != "master" and pipeline.parameters.skip_api_tests != true
      - test:
          matrix:
            parameters:
              testCommand:
                - "transaction-common"
                - "transaction-payment"
                - "product"
                - "customer"
                - "category"
                - "price"
                - "calendar"
                - "account"
                - "file"
                - "transaction-reimbursement"
                - "project"
                - "transaction-transfer"
                - "transaction-split"
                - "recipient"
                - "setting"
                - "transaction-deferred"
                - "user"
                - "transaction-draft"
          requires:
            - api_test_setup                
      # - test:
      #     serial-group: api-test1
      #     matrix:
      #       parameters:
      #         testCommand:
      #           ["transaction-common", "transaction-payment", "product"]
      #     requires:
      #       - api_test_setup
      # - test:
      #     serial-group: api-test2
      #     matrix:
      #       parameters:
      #         testCommand: ["customer", "category", "price"]
      #     requires:
      #       - api_test_setup
      # - test:
      #     serial-group: api-test3
      #     matrix:
      #       parameters:
      #         testCommand: ["calendar", "account", "file"]
      #     requires:
      #       - api_test_setup
      # - test:
      #     serial-group: api-test4
      #     matrix:
      #       parameters:
      #         testCommand:
      #           ["transaction-reimbursement", "project", "transaction-transfer"]
      #     requires:
      #       - api_test_setup
      # - test:
      #     serial-group: api-test5
      #     matrix:
      #       parameters:
      #         testCommand: ["transaction-split", "recipient", "setting"]
      #     requires:
      #       - api_test_setup
      # - test:
      #     serial-group: api-test6
      #     matrix:
      #       parameters:
      #         testCommand: ["transaction-deferred", "user", "transaction-draft"]
      #     requires:
      #       - api_test_setup
