import 'regenerator-runtime/runtime';
import { setAuthCommands } from '../api/auth/auth-commands';
import { setExpectCommands } from '../api/expect-commands';
import { setAccountTaskCommands } from '@household/test/api/account/commands/tasks';
import { setAccountRequestCommands } from '@household/test/api/account/commands/requests';
import { setAccountValidationCommands } from '@household/test/api/account/commands/validations';
import { setProjectRequestCommands } from '@household/test/api/project/commands/requests';
import { setProjectTaskCommands } from '@household/test/api/project/commands/tasks';
import { setProjectValidationCommands } from '@household/test/api/project/commands/validations';
import { setProductRequestCommands } from '@household/test/api/product/commands/requests';
import { setProductValidationCommands } from '@household/test/api/product/commands/validations';
import { setProductTaskCommands } from '@household/test/api/product/commands/tasks';
import { setRecipientRequestCommands } from '@household/test/api/recipient/commands/requests';
import { setRecipientTaskCommands } from '@household/test/api/recipient/commands/tasks';
import { setRecipientValidationCommands } from '@household/test/api/recipient/commands/validations';
import { setCategoryRequestCommands } from '@household/test/api/category/commands/requests';
import { setCategoryTaskCommands } from '@household/test/api/category/commands/tasks';
import { setCategoryValidationCommands } from '@household/test/api/category/commands/validations';
import { setTransactionRequestCommands } from '@household/test/api/transaction/commands/requests';
import { setTransactionTaskCommands } from '@household/test/api/transaction/commands/tasks';
import { setTransactionValidationCommands } from '@household/test/api/transaction/commands/validations';
import { setSettingRequestCommands } from '@household/test/api/setting/commands/requests';
import { setSettingTaskCommands } from '@household/test/api/setting/commands/tasks';
import { setSettingValidationCommands } from '@household/test/api/setting/commands/validations';
import { setUserRequestCommands } from '@household/test/api/user/commands/requests';
import { setUserTaskCommands } from '@household/test/api/user/commands/tasks';
import { setUserValidationCommands } from '@household/test/api/user/commands/validations';

setProjectRequestCommands();
setProjectTaskCommands();
setProjectValidationCommands();
setProductRequestCommands();
setProductValidationCommands();
setProductTaskCommands();
setRecipientRequestCommands();
setRecipientTaskCommands();
setRecipientValidationCommands();
setCategoryRequestCommands();
setCategoryTaskCommands();
setCategoryValidationCommands();
setTransactionRequestCommands();
setTransactionTaskCommands();
setTransactionValidationCommands();
setAccountTaskCommands();
setAccountValidationCommands();
setAccountRequestCommands();
setSettingRequestCommands();
setSettingTaskCommands();
setSettingValidationCommands();
setUserRequestCommands();
setUserTaskCommands();
setUserValidationCommands();
setAuthCommands();
setExpectCommands();
