import 'regenerator-runtime/runtime';
import { setAuthCommands } from '../api/auth/auth-commands';
import { setExpectCommands } from '../api/expect-commands';
import { setAccountTaskCommands } from '@household/test/api/account/commands/tasks';
import { setAccountRequestCommands } from '@household/test/api/account/commands/requests';
import { setAccountValidationCommands } from '@household/test/api/account/commands/validations';
import { setProjectRequestCommands } from '@household/test/api/project/commands/requests';
import { setProjectTaskCommands } from '@household/test/api/project/commands/tasks';
import { setProjectValidationCommands } from '@household/test/api/project/commands/validations';
import { setProductRequestCommands } from '@household/test/api/product/commands/requests';
import { setProductValidationCommands } from '@household/test/api/product/commands/validations';
import { setProductTaskCommands } from '@household/test/api/product/commands/tasks';
import { setRecipientRequestCommands } from '@household/test/api/recipient/commands/requests';
import { setRecipientTaskCommands } from '@household/test/api/recipient/commands/tasks';
import { setRecipientValidationCommands } from '@household/test/api/recipient/commands/validations';
import { setCategoryRequestCommands } from '@household/test/api/category/commands/requests';
import { setCategoryTaskCommands } from '@household/test/api/category/commands/tasks';
import { setCategoryValidationCommands } from '@household/test/api/category/commands/validations';
import { setCommonTransactionRequestCommands } from '@household/test/api/transaction/common/commands/requests';
import { setCommonTransactionTaskCommands } from '@household/test/api/transaction/common/commands/tasks';
import { setCommonTransactionValidationCommands } from '@household/test/api/transaction/common/commands/validations';
import { setSettingRequestCommands } from '@household/test/api/setting/commands/requests';
import { setSettingTaskCommands } from '@household/test/api/setting/commands/tasks';
import { setSettingValidationCommands } from '@household/test/api/setting/commands/validations';
import { setUserRequestCommands } from '@household/test/api/user/commands/requests';
import { setUserTaskCommands } from '@household/test/api/user/commands/tasks';
import { setUserValidationCommands } from '@household/test/api/user/commands/validations';
import { setFileRequestCommands } from '@household/test/api/file/commands/requests';
import { setFileTaskCommands } from '@household/test/api/file/commands/tasks';
import { setFileValidationCommands } from '@household/test/api/file/commands/validations';
import { setDeferredTransactionValidationCommands } from '@household/test/api/transaction/deferred/commands/validations';
import { setPaymentTransactionRequestCommands } from '@household/test/api/transaction/payment/commands/requests';
import { setPaymentTransactionValidationCommands } from '@household/test/api/transaction/payment/commands/validations';
import { setReimbursementTransactionValidationCommands } from '@household/test/api/transaction/reimbursement/commands/validations';
import { setSplitTransactionRequestCommands } from '@household/test/api/transaction/split/commands/requests';
import { setSplitTransactionValidationCommands } from '@household/test/api/transaction/split/commands/validations';
import { setTransferTransactionRequestCommands } from '@household/test/api/transaction/transfer/commands/requests';
import { setTransferTransactionValidationCommands } from '@household/test/api/transaction/transfer/commands/validations';
import { setDraftTransactionRequestCommands } from '@household/test/api/transaction/draft/commands/requests';
import { setDraftTransactionTaskCommands } from '@household/test/api/transaction/draft/commands/tasks';
import { setDraftTransactionValidationCommands } from '@household/test/api/transaction/draft/commands/validations';

setProjectRequestCommands();
setProjectTaskCommands();
setProjectValidationCommands();
setProductRequestCommands();
setProductValidationCommands();
setProductTaskCommands();
setRecipientRequestCommands();
setRecipientTaskCommands();
setRecipientValidationCommands();
setCategoryRequestCommands();
setCategoryTaskCommands();
setCategoryValidationCommands();
setCommonTransactionRequestCommands();
setCommonTransactionTaskCommands();
setCommonTransactionValidationCommands();
setPaymentTransactionRequestCommands();
setPaymentTransactionValidationCommands();
setSplitTransactionRequestCommands();
setSplitTransactionValidationCommands();
setDeferredTransactionValidationCommands();
setReimbursementTransactionValidationCommands();
setTransferTransactionRequestCommands();
setTransferTransactionValidationCommands();
setDraftTransactionRequestCommands();
setDraftTransactionTaskCommands();
setDraftTransactionValidationCommands();
setAccountTaskCommands();
setAccountValidationCommands();
setAccountRequestCommands();
setSettingRequestCommands();
setSettingTaskCommands();
setSettingValidationCommands();
setUserRequestCommands();
setUserTaskCommands();
setUserValidationCommands();
setFileRequestCommands();
setFileTaskCommands();
setFileValidationCommands();
setAuthCommands();
setExpectCommands();
