openapi: "3.0.0"
info:
  title: Account components
  version: 1.0.0
components:
  schemas:
    AccountId:
      type: object
      required:
        - accountId
      properties:
        accountId:
          type: string
          minLength: 1
    IsOpen:
      type: object
      required:
        - isOpen
      properties:
        isOpen:
          type: boolean
    Name:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
    Currency:
      type: object
      required:
        - currency
      properties:
        currency:
          type: string
          minLength: 1
    AccountType:
      type: object
      required:
        - accountType
      properties:
        accountType:
          type: string
          enum:
            - bankAccount
            - cash
            - creditCard
            - loan
            - cafeteria
    Owner:
      type: object
      required:
        - owner
      properties:
        owner:
          type: string
          minLength: 1
    FullName:
      type: object
      required:
        - fullName
      properties:
        fullName:
          type: string
          minLength: 1
    Base:
      allOf:
        - $ref: "#/components/schemas/Name"
        - $ref: "#/components/schemas/Currency"
        - $ref: "#/components/schemas/AccountType"
        - $ref: "#/components/schemas/Owner"
    Balance:
      type: object
      required:
        - balance
      properties:
        balance:
          type: number
    Response:
      allOf:
        - $ref: "#/components/schemas/AccountId"
        - $ref: "#/components/schemas/IsOpen"
        - $ref: "#/components/schemas/Base"
        - $ref: "#/components/schemas/Balance"
        - $ref: "#/components/schemas/FullName"
    Report:
      allOf:
        - $ref: "#/components/schemas/AccountId"
        - $ref: "#/components/schemas/FullName"
        - $ref: "#/components/schemas/Currency"
    Request:
      $ref: "#/components/schemas/Base"
