openapi: "3.0.0"
info:
  title: File components
  version: 1.0.0
components:
  schemas:
    FileType:
      type: object
      required:
        - fileType
      properties:
        fileType:
          type: string
          enum:
            - otp
            - erste
            - revolut
    Url:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: url
    FileId:
      type: object
      required:
        - fileId
      properties:
        fileId:
          type: string
          minLength: 1
