openapi: "3.1.0"
info:
  title: Hairdressing components
  version: 1.0.0
components:
  schemas:
    PriceId:
      type: object
      required:
        - priceId
      properties:
        priceId:
          type: string
          minLength: 1
    Base:
      type: object
      required:
        - name
        - amount
      properties:
        name:
          type: string
          minLength: 1
        amount:
          type: integer
          exclusiveMinimum: 0

    Response:
      allOf:
        - $ref: "#/components/schemas/PriceId"
        - $ref: "#/components/schemas/Base"
    Request:
      allOf:
        - $ref: "#/components/schemas/Base"
