openapi: "3.1.0"
info:
  title: Hairdressing price components
  version: 1.0.0
components:
  schemas:
    PriceId:
      type: object
      required:
        - priceId
      properties:
        priceId:
          type: string
          minLength: 1

    Base:
      type: object
      required:
        - name
        - amount
        - unitOfMeasurement
      properties:
        name:
          type: string
          minLength: 1
        amount:
          type: integer
        unitOfMeasurement:
          type: string
          enum:
            - db
            - g
            - óra

    Response:
      allOf:
        - $ref: "#/components/schemas/PriceId"
        - $ref: "#/components/schemas/Base"
    Request:
      allOf:
        - $ref: "#/components/schemas/Base"
