openapi: "3.1.0"
info:
  title: Hairdressing price components
  version: 1.0.0
components:
  schemas:
    PriceId:
      type: object
      properties:
        priceId:
          type: string
          minLength: 1
    PriceId.Required:
      type: object
      required:
        - priceId

    Base:
      type: object
      required:
        - name
        - amount
      properties:
        name:
          type: string
          minLength: 1
        amount:
          type: integer

    UnitOfMeasurement:
      type: object
      properties:
        unitOfMeasurement:
          type: string
          enum:
            - db
            - g
            - óra
    UnitOfMeasurement.Required:
      type: object
      required:
        - unitOfMeasurement

    Response:
      allOf:
        - $ref: "#/components/schemas/PriceId"
        - $ref: "#/components/schemas/PriceId.Required"
        - $ref: "#/components/schemas/Base"
        - $ref: "#/components/schemas/UnitOfMeasurement"
        - $ref: "#/components/schemas/UnitOfMeasurement.Required"
    Request:
      allOf:
        - $ref: "#/components/schemas/Base"
        - $ref: "#/components/schemas/UnitOfMeasurement"
        - $ref: "#/components/schemas/UnitOfMeasurement.Required"
