openapi: "3.1.0"
info:
  title: Report components
  version: 1.0.0
components:
  schemas:
    Request:
      type: array
      minItems: 1
      items:
        allOf:
          - type: object
            required:
              - include
            properties:
              include:
                type: boolean
                default: true
          - oneOf:
              - type: object
                required:
                  - filterType
                properties:
                  filterType:
                    type: string
                    enum:
                      - account
                      - category
                      - project
                      - product
                      - recipient
                  items:
                    type: array
                    minItems: 1
                    items:
                      type: string
                      minLength: 1
              - type: object
                required:
                  - filterType
                properties:
                  filterType:
                    type: string
                    enum:
                      - issuedAt
                  from:
                    type: string
                    format: date-time
                  to:
                    type: string
                    format: date-time
